config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root 'events#index'

  resources :events do
    resources :comments, only: %i[create destroy]
    resources :subscriptions, only: %i[create destroy]
    resources :photos, only: %i[create destroy]
    post :show, on: :member
  end

  resources :users, only: %i[show edit update]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user, dependent: :destroy
  has_many :photos, dependent: :destroy

  validates :address, :datetime, presence: true
  validates :title, presence: true, length: { maximum: 255 }
  validates :pincode, length: { maximum: 10 }

  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_event, only: %i[show edit update destroy]

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  # GET /events
  def index
    @events = policy_scope(Event)
  end

  # GET /events/1
  def show
    if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
      cookies.permanent["event_#{@event.id}_pincode"] = params[:pincode]
    end
    authorize @event
  rescue Pundit::NotAuthorizedError
    flash.now[:alert] = t('controllers.events.wrong_pincode') if params[:pincode].present?
    render 'pincode_form'
  end

  # GET /events/new
  def new
    @event = current_user.events.build
    authorize @event
  end

  # GET /events/1/edit
  def edit
    authorize @event
  end

  # POST /events
  def create
    @event = current_user.events.build(event_params)

    authorize @event

    if @event.save
      redirect_to @event, notice: t('controllers.events.created')
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    authorize @event

    if @event.update(event_params)
      redirect_to @event, notice: t('controllers.events.updated')
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    authorize @event

    @event.destroy
    redirect_to @event, notice: t('controllers.events.destroyed')
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
  end
end

app/views/events/_event.html.erb
<div class="col-sm-10 col-md-12 mx-auto d-block mt-3">
  <div class="thumbnail">
    <%= content_tag 'div', '', class: 'event-background',
                    style: "background-image: url(#{asset_pack_path('media/images/event_thumb.jpg')})" %>
    <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description text-left">
          <% if current_user_can_edit_event?(event) %>
            <h3><%= link_to event.title, event_path(event) %>
              <small>(<%= t('my_event') %>)</small></h3>
          <% else %>
            <h3><%= link_to event.title, event_path(event) %>
              <small>(<%= t('organizer') %> <%= link_to event.user.name, user_path(event.user) %>)</small></h3>
          <% end %>
          <h3><small><%= l event.datetime, format: :long %></small></h3>
          <div class="buffer-both"><%= event.address %></div>
        </div>
        <div class="event-description text-left">
          <% if event.subscribers.count > 0 %>
            <b><%= t('subscribers') %></b>
            <% event.subscribers.each do |user| %>
              <%= link_to image_tag(user_avatar(user), class: 'img-icon', title: user.name), user_path(user) %>
            <% end %>
          <% end %>
        </div>

        <div class="event-description text-left">
          <% if event.comments.count > 0 %>
            <b><%= t('comments') %> <%= event.comments.count %></b>
          <% end %>
        </div>

        <div class="event-description text-left">
          <% if event.photos.count > 0 %>
            <b><%= t('photos') %> <%= event.photos.count %></b>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :datetime %>
    <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :pincode %>
    <%= f.text_field :pincode, class: 'form-control' %>
  </div>

  <div class="actions form-group">
    <%= f.submit t('save'), class: 'btn btn-primary btn-block' %>
    <%= link_to t('back'), :back, class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1><%= t("edit_event") %></h1>

<div class="row">
  <div class="col-md-10 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<h1><%= t("events_list") %></h1>

<div class="buffer-both">
  <%= link_to t('create_event'), new_event_path, class: 'btn btn-success' %>
</div>

<div class="row buffer-bottom">
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1><%= t('create_event') %></h1>

<div class="row">
  <div class="col-md-10 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/events/pincode_form.html.erb
<h1><%= t('pincode_access') %></h1>

<%= form_for '', method: :post do |f| %>
  <div class="form-group">
    <%= f.password_field :pincode %>
    <%= f.submit t('send'), class: 'btn btn-primary' %>
  </div>

  <div class="actions form-group">
    <%= link_to t('back'), root_path, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/events/show.html.erb
<div class="event">
  <div class="event-info row">
    <div class="col-md-12">
      <%= content_tag 'div', '', class: 'event-background',
                      style: "background-image: url(#{asset_pack_path('media/images/event.jpg')})" %>
      <div class="event-info-inner row">
        <div class="col-md-9 mt-1">
          <div class="event-description">
            <% if policy(@event).edit? %>
              <h3><%= link_to @event.title, event_path(@event) %> <small>(<%= t('my_event') %>)</small></h3>
            <% else %>
              <h3><%= link_to @event.title, event_path(@event) %>
                <small>(<%= t('organizer') %> <%= link_to @event.user.name, user_path(@event.user) %>)</small></h3>
            <% end %>
            <h3><%= l @event.datetime, format: :long %></h3>
            <h3><small><%= link_to @event.address, "https://www.google.com.ua/maps/search/#{@event.address}" %></small>
            </h3>
            <p><%= @event.description %></p>
          </div>

          <div class="event-description">
            <% if @event.subscriptions.count > 0 %>
              <p><b><%= t('will_go') %></b><%= render partial: 'subscriptions/subscription',
                                                      collection: @event.subscriptions.except(@new_subscription) %></p>
            <% end %>
          </div>
          <% if policy(@event).edit? %>
            <div class="buffer-top">
              <%= link_to t('edit'), edit_event_path(@event), class: 'btn btn-secondary mb-2' %>
              <%= link_to t('delete'), event_path(@event), method: :delete, data: { confirm: t('are_you_sure') }, class: 'btn btn-secondary mb-2' %>
            </div>
          <% end %>
        </div>

        <div class="col-md-3 mt-2">
          <div class="event-subscription-form">
            <% if !policy(@event).edit? %>
              <%= render partial: 'subscriptions/form',
                         locals: { subscription: @new_subscription || @event.subscriptions.build } %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-9">
    <%= content_tag('div', '', id: 'map', style: "width: 600px; height: 400px", data: { address: @event.address }) %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="event-comments buffer-top">
      <h3><%= t('event_photos') %></h3>
      <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
      <div class="buffer-both">
        <%= render partial: 'photos/form', locals: { photo: @new_photo || @event.photos.build } %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-9">
    <div class="event-comments buffer-top">
      <%= render partial: 'comments/form', locals: { comment: @new_comment || @event.comments.build } %>
      <div class="buffer-both">
        <%= render partial: 'comments/comment', collection: @event.comments.except(@new_comment) %>
      </div>
    </div>
  </div>
</div>