config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root 'events#index'

  resources :events do
    resources :comments, only: %i[create destroy]
    resources :subscriptions, only: %i[create destroy]
    resources :photos, only: %i[create destroy]
    post :show, on: :member
  end

  resources :users, only: %i[show edit update]
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates :image, presence: true, file_size: { less_than_or_equal_to: 5.megabyte }

  mount_uploader :image, PhotoUploader
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_event, only: %i[create destroy]
  before_action :set_photo, only: %i[destroy]

  def create
    @new_photo = @event.photos.build(photo_params)
    @new_photo.user = current_user

    if @new_photo.save
      EventMailerJob.perform_later(@new_photo)

      redirect_to @event, notice: t('controllers.photos.created')
    else
      render 'events/show', alert: t('controllers.photos.error')
    end
  end

  def destroy
    message = { notice: t('controllers.photos.destroyed') }

    if current_user_can_edit_event?(@photo)
      @photo.destroy!
    else
      message = { alert: t('controllers.photos.error') }
    end

    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_photo
    @photo = @event.photos.find(params[:id])
  end

  def photo_params
    params.fetch(:photo, {}).permit(:image, :image_cache)
  end
end

app/views/photos/_form.html.erb
<%= form_for [@event, photo], html: {multipart: true} do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: photo} %>

  <div class="form-group">
    <%= f.label :photo %><br>
    <%= image_tag(photo.image.thumb.url, alt: 'Photo') if photo.image? %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %> <%= f.submit t('upload'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<span class="buffer-bottom">
  <%= link_to image_tag(photo.image.thumb.url), photo.image.url, data: {toggle: "lightbox", gallery:
    "ukrbbq-gallery"} %>
  <% if current_user_can_edit_event?(photo) %>
    <%= link_to(fa_icon('trash'), event_photo_path(photo.event, photo),
                method: :delete, data: { confirm: t('are_you_sure') }) %>
  <% end %>
</span>